"""add base and two tables

Revision ID: 0e76e537a25c
Revises: 
Create Date: 2020-04-30 17:10:10.448917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e76e537a25c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.BIGINT(), nullable=True),
    sa.Column('eggs_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_address'), 'order', ['address'], unique=False)
    op.create_index(op.f('ix_order_customer'), 'order', ['customer'], unique=False)
    op.create_index(op.f('ix_order_date_created'), 'order', ['date_created'], unique=False)
    op.create_index(op.f('ix_order_eggs_count'), 'order', ['eggs_count'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=True)
    op.create_index(op.f('ix_order_phone'), 'order', ['phone'], unique=False)
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_date_created'), 'price', ['date_created'], unique=False)
    op.create_index(op.f('ix_price_id'), 'price', ['id'], unique=True)
    op.create_index(op.f('ix_price_price'), 'price', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_price'), table_name='price')
    op.drop_index(op.f('ix_price_id'), table_name='price')
    op.drop_index(op.f('ix_price_date_created'), table_name='price')
    op.drop_table('price')
    op.drop_index(op.f('ix_order_phone'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_eggs_count'), table_name='order')
    op.drop_index(op.f('ix_order_date_created'), table_name='order')
    op.drop_index(op.f('ix_order_customer'), table_name='order')
    op.drop_index(op.f('ix_order_address'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
