"""order table

Revision ID: a67137587ec3
Revises: 
Create Date: 2020-04-27 11:24:45.537025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67137587ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.BIGINT(), nullable=True),
    sa.Column('eggs_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_address'), 'order', ['address'], unique=False)
    op.create_index(op.f('ix_order_customer'), 'order', ['customer'], unique=False)
    op.create_index(op.f('ix_order_eggs_count'), 'order', ['eggs_count'], unique=False)
    op.create_index(op.f('ix_order_phone'), 'order', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_phone'), table_name='order')
    op.drop_index(op.f('ix_order_eggs_count'), table_name='order')
    op.drop_index(op.f('ix_order_customer'), table_name='order')
    op.drop_index(op.f('ix_order_address'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
